name: Mirror main to public repo

on:
  push:
    branches:
      - main

jobs:
  mirror:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout private repo
        uses: actions/checkout@v4

      - name: Push to public repository
        env:
          TOKEN: ${{ secrets.PUBLIC_REPO_TOKEN }}
          REPO: ${{ secrets.PUBLIC_REPO_SLUG }}
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"

          git remote add public "https://x-access-token:${TOKEN}@github.com/${REPO}.git"
          git push --force public main:main
