name: Mirror main to public repo

on:
  push:
    branches:
      - main

jobs:
  mirror:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout private repo
        uses: actions/checkout@v4

      - name: Configure Git
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"

      - name: Push to public repository
        env:
          TOKEN: ${{ secrets.PUBLIC_REPO_TOKEN }}
          REPO: ${{ secrets.PUBLIC_REPO_SLUG }}
        run: |
          REMOTE_URL="https://x-access-token:$TOKEN@github.com/$REPO.git"
          git remote add public "$REMOTE_URL"
          git push --force public main:main