name: Mirror main to public repo

on:
  push:
    branches:
      - main

jobs:
  mirror:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout private repo
        uses: actions/checkout@v4

      - name: Configure Git
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"

      - name: Push main to public repository
        env:
          PUBLIC_REPO_URL: ${{ secrets.PUBLIC_REPO_URL }}
        run: |
          git remote add public "$PUBLIC_REPO_URL"
          git push --force public main:main
