name: Mirror main to public repo

on:
  push:
    branches:
      - main

jobs:
  mirror:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout private repo
        uses: actions/checkout@v4

      - name: Push to public repository
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"

          REMOTE_URL="https://x-access-token:${{ secrets.PUBLIC_REPO_TOKEN }}@github.com/${{ secrets.PUBLIC_REPO_SLUG }}.git"
          echo "Pushing to: $REMOTE_URL (token masked)"
          git remote add public "$REMOTE_URL"
          git push --force public main:main
